### ISSUE TITLE
请问Readme说明里的Docker镜像要从哪里下载？

### ISSUE THREAD

**Issue by kongzhenhao** [tapdata/tapdata#1208]
### Comment

请问Readme说明里的以下Docker镜像要从哪里下载？
docker run -itd -p 3030:3030 github.com/tapdata/tapdata-opensource:latest bash

**Comment by Naylor55** [comment]
报404 了， 是删除了嘛？
docker run -itd -p 3030:3030 github.com/tapdata/tapdata-opensource:latest



Unable to find image 'github.com/tapdata/tapdata-opensource:latest' locally
docker: Error response from daemon: error parsing HTTP 404 response body: no error details found in HTTP response body: "{\"error\":\"Not Found\"}".
See 'docker run --help'.

**Comment by xbsura** [comment]
您可以看下最新的 readme, 已经更新了完整的镜像包

**Comment by xbsura** [comment]
您可以看下最新的 readme, 已经更新了完整的镜像包
