### ISSUE TITLE
对于全量任务，是否支持停止之后，重新启动从上一个位置开始同步，而且还能保证数据的不丢失？

### ISSUE THREAD

**Issue by Harries** [tapdata/tapdata#1329]
### Comment

我想咨询，对于全量任务，是否支持停止之后，重新启动从上一个位置开始同步，而且还能保证数据的不丢失？

**Comment by xbsura** [comment]
目前对于全量任务, 如果是多表复制任务, 会从未完成的表开始运行, 如果是单表, 会全部同步单表, 没有做表内断点
