### ISSUE TITLE
tapdata cloud同步数据测试通过了 但最终还是失败了

### ISSUE THREAD

**Issue by CoconuterTATA** [tapdata/tapdata#139]
我在连接管理里面测试源数据库的连接情况，显示没有任何问题，目标数据库测试也没问题，但在执行同步任务的时候连接失败
`Connect to source mysql failed, config: {snapshot.locking.mode=none, restRetryTime=3, connector.class=io.debezium.connector.mysql.MySqlConnector, dataFlow.id=634d7038c0c94167270a2910, max.queue.size=8000, job.id=634d703bc162f518b15885f2, table.whitelist=demo.student2,demo.student1, database.history.sourceConnId=6345927d8eb5d14b4f74047e, accessCode=1e611290a0134b4dacd4da56bdffcb8af8aaf012f6aa4a0da887b066db8346c3, poll.interval.ms=500, database.history.baseURL=https://cloud.tapdata.net/console/tm/api/, database.history.skip.unparseable.ddl=true, job.name=测试_1, database.whitelist=demo, database.history.job.id=634d703bc162f518b15885f2, binlogStartPoint=true, database.user=test, database.binlog.position={"filename":"master1-bin.000001","position":2335,"gtidSet":null}, database.history.dataFlowId=634d7038c0c94167270a2910, offset.storage=io.tapdata.common.MongoOffsetBackingStore, database.server.id=1181781442, roleId=0, database.server.name=634d703bc162f518b15885f2, userId=63458e7ec162f518b171e383, database.port=3307, database.history.roleId=0, threadName=Connector runner-测试_1-[634d703bc162f518b15885f2], offset.flush.interval.ms=60000, database.history.accessCode=1e611290a0134b4dacd4da56bdffcb8af8aaf012f6aa4a0da887b066db8346c3, baseURL=https://cloud.tapdata.net/console/tm/api/, database.hostname=my ip addr, database.password=********, database.history.userId=63458e7ec162f518b171e383, name=634d703bc162f518b15885f2, database.history.store.only.monitored.tables.ddl=true, max.batch.size=1000, database.history.restRetryTime=3, database.history=io.tapdata.common.MongoDatabaseHistoryBackingStore, snapshot.mode=schema_only}, err: Error reading MySQL variables: Access denied for user 'test'@'my ip addr' (using password: YES), stacks: org.apache.kafka.connect.errors.ConnectException: Error reading MySQL variables: Access denied for user 'test'@'my ip addr' (using password: YES) at io.debezium.connector.mysql.MySqlJdbcContext.querySystemVariables(MySqlJdbcContext.java:329) at io.debezium.connector.mysql.MySqlJdbcContext.readMySqlSystemVariables(MySqlJdbcContext.java:309) at io.debezium.connector.mysql.MySqlTaskContext.<init>(MySqlTaskContext.java:81) at io.debezium.connector.mysql.MySqlTaskContext.<init>(MySqlTaskContext.java:54) at io.debezium.connector.mysql.MySqlConnectorTask.createAndStartTaskContext(MySqlConnectorTask.java:428) at io.debezium.connector.mysql.MySqlConnectorTask.initTaskContext(MySqlConnectorTask.java:359) at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:169) at io.debezium.tapdata.connector.common.BaseSourceTask.start(BaseSourceTask.java:105) at io.debezium.tapdata.embedded.EmbeddedEngine.run(EmbeddedEngine.java:815) at io.tapdata.manager.ConnectorJobManager.lambda$createMySqlEngine$5(ConnectorJobManager.java:921) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829) Caused by: java.sql.SQLException: Access denied for user 'test'@'my ip addr' (using password: YES) at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833) at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) at com.tapdata.constant.JdbcUtil.retryByMaxConnect(JdbcUtil.java:2083) at io.debezium.tapdata.jdbc.JdbcConnection.lambda$patternBasedFactory$1(JdbcConnection.java:174) at io.debezium.tapdata.jdbc.JdbcConnection.connection(JdbcConnection.java:786) at io.debezium.tapdata.jdbc.JdbcConnection.connection(JdbcConnection.java:781) at io.debezium.tapdata.jdbc.JdbcConnection.connect(JdbcConnection.java:320) at io.debezium.connector.mysql.MySqlJdbcContext.querySystemVariables(MySqlJdbcContext.java:316) ... 12 more`

**Comment by xbsura** [comment]
这里只跑全量, 数据可以同步成功吗?

**Comment by CoconuterTATA** [comment]
@xbsura 只跑全量，数据同步成功了，但我主要的需求还是能做到实时同步数据，只跑全量它只同步一次不符合需求。。

**Comment by xbsura** [comment]
了解, 这里应该是配置的账号权限不足, 比如不能执行一些类似: SHOW VARIABLES 的命令, 在连接测试时没有发现这些类型的权限不足, 可以尝试给更高权限的账号做同步任务来解决

**Comment by CoconuterTATA** [comment]
我通过命令`show grants for test;` 查询了我进行同步的账号权限，它显示
` GRANT ALL PRIVILEGES ON *.* TO `test`@`%` IDENTIFIED BY PASSWORD '*23AE809DDACAF96AF0FD78ED04B6A265E05AA257' WITH GRANT OPTION`
我应该是已经授予了所有的权限。测试`show variables`命令也能够正常得到结果

**Comment by tjworks** [comment]
close inactive issue
