### ISSUE TITLE
tapdata cloud 从本地mysql到本地sqlserver的全量加增量同步，全量同步可以正常实现，增量同步实现不了，也没报错

### ISSUE THREAD

**Issue by phy7499** [tapdata/tapdata#146]
我使用tapdata cloud进行从mysql到sqlserver的全量加增量的数据同步
在全量同步完成后，在增量同步的过程中，我去本地的mysql添加了一行数据，但是在sqlserver中没有相应的行的添加（附件是运行日志，从22点9分左右到22点21分多的运行日志，我是在22点13分左右在MySQL中添加了一行，[日志.txt](https://github.com/tapdata/tapdata/files/9852612/default.txt)）
里程碑是这样显示的（我怀疑是可能是因为增量读取模式在22点10分就结束了，所以增量传输不了？）：
![image](https://user-images.githubusercontent.com/116562850/197553135-5dcea13f-7476-4f55-8bde-e4e1328920c2.png)
全量是正常的：
![image](https://user-images.githubusercontent.com/116562850/197553350-a02f8e74-8046-42b7-a0e2-c5ca08e31eba.png)
所以我搞不清我这些操作问题出在了那里，该怎样解决？求解答

**Comment by xbsura** [comment]
好的, 正在看

**Comment by xbsura** [comment]
看任务日志, 没有发现可以进行增量同步的表, sys 库是系统库, 产品暂时不支持对系统库进行实时同步
