### ISSUE TITLE
mysql 字段默认值为不支持 current_timestamp  关键字

### ISSUE THREAD

**Issue by Harries** [tapdata/tapdata#1667]
### Comment

mysql 字段默认值为不支持 current_timestamp  关键字

### 插件实现的源功能 Implemented Features - as Source

- [ ] 全量读 source-feature-full-sync
- [ ] 增量读 source-feature-cdc
- [ ] 全量总数统计 source-feature-count
- [ ] 增量指定时间 source-feature-cdc-time-point
- [ ] 高级查询 source-feature-advance-query
- [ ] 查询索引 source-feature-load-index
- [ ] 加载模型 source-feature-load-schema
- [ ] 获取表 source-feature-table-names
- [ ] DDL读取 source-feature-ddl

### 插件实现的目标功能 Implemented Features - as Target

- [ ] 插入事件 target-feature-insert
- [ ] 删除事件 target-feature-delete
- [ ] 更新事件 target-feature-update
- [ ] 清除数据 target-feature-clear-data
- [X] 创建表 target-feature-create-table
- [ ] 删除表 target-feature-drop-table
- [ ] 创建索引 target-feature-create-index
- [ ] 删除索引 target-feature-drop-index
- [ ] DDL写入 target-feature-ddl

**Comment by xbsura** [comment]
你好, 这个需求我们目前还没有计划去开发, 这主要涉及到 current_timestamp 这个方法, 他在不同的数据库里面需要进行不同的实现, 因此对于 默认值 的方法支持, 现在都是没有去做的, 但是这不影响您的数据集成过程, 默认值也会被同步到目标中

**Comment by tjworks** [comment]
No plan to implement
