### ISSUE TITLE
COPY iengine/ /tapdata/apps error

### ISSUE THREAD

**Issue by shmilyhcl** [tapdata/tapdata#1680]
### Comment

按照文档中的 Install 后，卡在All Done, Please Visit http://localhost:3000，进入docker中，看到COPY iengine/ /tapdata/apps error等几个步骤报错。

**Comment by shmilyhcl** [comment]
明细为COPY manager/ /tapdata/apps/manager/ # buildkit
COPY iengine/ /tapdata/apps/iengine/ # buildkit
COPY pdk.jar /tapdata/apps/lib/pdk.jar # buildkit

**Comment by 32073955** [comment]
麻烦问一下您的详细操作步骤是什么？就是您执行了那些命令install的，之后如何启动的？

**Comment by shmilyhcl** [comment]
执行命令
# Clone tapdata repo
git clone https://github.com/tapdata/tapdata.git
# Get start!
bash build/quick-use.sh
系统环境为Ventura 13.6.3 ，Docker为v4.26.1

**Comment by xbsura** [comment]
最新的 readme 已经发布, 您可以参考下
