### ISSUE TITLE
Deployment Documentation Issues

### ISSUE THREAD

**Issue by zhbdesign** [tapdata/tapdata#1938]
### Comment

Building.md lacks a cluster deployment step, tapdata-agent.jar needs to be replaced with ie.jar, the deployment document is still launched directly from the binary package of release, and also needs to be modified

**Comment by xbsura** [comment]
OK, I will correct it, and add cluster deployment document

**Comment by zhbdesign** [comment]
> OK, I will correct it, and add cluster deployment document

thanks
