### ISSUE TITLE
Incremental data synchronization is very slow.

### ISSUE THREAD

**Issue by realxujiang** [tapdata/tapdata#1949]
### Comment

Using the official tapdata Docker image, the QPS is very low during incremental synchronization, only reaching 2100 QPS/s. Network issues have been ruled out; Tapdata is in a separate container, and the MySQL database is in another separate container on the same host machine, so there are no cross-network issues. The environment information is as follows:
```
root@adcd22a40318:/tapdata/apps# uname -m
aarch64
root@adcd22a40318:/tapdata/apps# uname -a
Linux adcd22a40318 6.4.16-linuxkit #1 SMP PREEMPT Thu Nov 16 10:49:20 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
root@adcd22a40318:/tapdata/apps# java -version
java version "1.8.0_401"
Java(TM) SE Runtime Environment (build 1.8.0_401-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.401-b10, mixed mode)

root@adcd22a40318:/tapdata/apps# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 07:06 ?        00:00:00 /tini -- bash -c /tapdata/docker-entrypoint.sh
root         7     1  0 07:06 ?        00:00:00 /bin/bash /tapdata/docker-entrypoint.sh
root        15     1  3 07:06 ?        00:05:14 mongod --dbpath=/tapdata/data/db/ --replSet=rs0 --wiredTigerCacheSizeGB=1 --bind_ip_all --logpath=/tapdata/data/logs/mongod.l
root       202     1  9 07:06 ?        00:14:56 java -jar -Dserver.port=3030 -server components/tm.jar --spring.config.additional-location=file:etc/ --logging.config=file:et
root       526     7  0 07:07 ?        00:00:00 sleep infinity
root      1077     0  0 07:12 pts/0    00:00:00 bash
root      1960     0  0 08:48 pts/1    00:00:00 bash
root      6219     1 15 09:04 pts/1    00:06:15java -jar components/tapdata-agent.jar
root      6955  1077  0 09:43 pts/0    00:00:00 ps -ef
```

### Appendix
* 1. Task Execution Interface Diagram
![console-image](https://github.com/tapdata/tapdata/assets/12759642/e84683b7-44c2-45f0-a5d2-35245f581bdf)

### 插件实现的源功能 Implemented Features - as Source

- [X] 全量读 source-feature-full-sync
- [X] 增量读 source-feature-cdc
- [ ] 全量总数统计 source-feature-count
- [ ] 增量指定时间 source-feature-cdc-time-point
- [ ] 高级查询 source-feature-advance-query
- [ ] 查询索引 source-feature-load-index
- [ ] 加载模型 source-feature-load-schema
- [ ] 获取表 source-feature-table-names
- [ ] DDL读取 source-feature-ddl

### 插件实现的目标功能 Implemented Features - as Target

- [X] 插入事件 target-feature-insert
- [ ] 删除事件 target-feature-delete
- [ ] 更新事件 target-feature-update
- [ ] 清除数据 target-feature-clear-data
- [ ] 创建表 target-feature-create-table
- [ ] 删除表 target-feature-drop-table
- [ ] 创建索引 target-feature-create-index
- [ ] 删除索引 target-feature-drop-index
- [ ] DDL写入 target-feature-ddl

**Comment by xbsura** [comment]
jdk in docker images is from oracle 1.8, which is much slower than openjdk, will fix it in next release
