### ISSUE TITLE
社区版问题有点多

### ISSUE THREAD

**Issue by yimengyisheng** [tapdata/tapdata#2180]
bug一大堆，
点开源有权限的页面也一直弹窗开源版本不支持
创建的任务列表看不见，导致数据源无法删除

**Comment by xbsura** [comment]
嗯, 这个问题已经了解了, 一个开源的功能包含了闭源特性, 没控制好, 这个版本发布后会修复

目前影响的范围是 数据复制 那个页面打不开, 非常抱歉, 修复了我联系你

**Comment by xbsura** [comment]
你好 @yimengyisheng 这个问题主要是由于我们最新的镜像 tag 没有更新导致的, 您可以使用 ghcr.io/tapdata/tapdata:v3.11.0-66b19c81 来使用最新的版本, 或者重新 pull 一下 latest tag, 这个镜像已经更新了

我们每两周都会 push 最新的镜像到仓库, 但是忘记了更新了 latest 这个 tag

非常抱歉, 您可以验证下这个问题
