### ISSUE TITLE
社区版：时间类型处理有问题

### ISSUE THREAD

**Issue by wukong567** [tapdata/tapdata#2252]
1. 表结构被变更
**源端**：
       `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
       `lastUpdated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
**目标端**：
       `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
       `lastUpdated` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',

2. date类型转化有问题，改为datetime类型同步正常
**表结构**
  `mDate` date DEFAULT NULL COMMENT '生产日期',
  `eDate` date DEFAULT NULL COMMENT '失效日期',
  `aDate` date DEFAULT NULL COMMENT '入仓日期',

```
           mDate     eDate               aDate
 源端                  2099-01-01      2024-01-20
目标                   1962-11-25      2024-01-20
```

**Comment by xbsura** [comment]
收到了, 谢谢你的反馈

**Comment by jarad0628** [comment]
第一个问题，默认函数是不支持同步的，因为有很多异构场景需要适配，目前范围难以把控

**Comment by jarad0628** [comment]
第二个问题，确实是integer溢出的问题，已在该PR中修复
https://github.com/tapdata/tapdata-connectors/pull/389

**Comment by xbsura** [comment]
这里解释下这两个问题:
1. 在进行数据同步的时候, 有两个原因导致默认的函数, 以及一些自增属性在目标端被去除, 一方面是我们尽最大可能避免数据在两侧生成的情况, 这样会导致可能的数据不一致, 另一方面是我们的产品是支持异构同步的, 并没有对同构做特别的支持, 所以默认函数值是被取消的, 在数据同步的时候, 数值不会出错, 您如果真的有需要, 可以在目标数据表中手动增加默认值

2. 这是类型转换中的 BUG, 感谢您的反馈, 修复会在下次版本中被发布
