### ISSUE TITLE
web界面后续会开源吗

### ISSUE THREAD

**Issue by huzk8** [tapdata/tapdata#4]
目前只能通过shell来启动tapdata任务，后续web界面会开源吗

**Comment by xbsura** [comment]
感谢关注

目前这边的商业化考虑的范围有几个:
1. 可视化前端
2. 部分闭源数据库连接器
3. 一些企业级的安全审计, 监控告警, 权限等等个人用不太上的功能
4. 一些企业级管理能力

不排除 Web 开源的可能, 但是目前还不在时间线上, 如果开源这个项目运作上比较好, 开源的范围会逐渐扩大
