### ISSUE TITLE
SimpleDateFormat is not thread-safe

### ISSUE THREAD

**Issue by lanicc** [tapdata/tapdata#41]
Date formats are not synchronized. It is recommended to create separate format instances for each thread. If multiple threads access a format concurrently, it must be synchronized externally.

https://github.com/tapdata/tapdata/blob/e70ba7d54986f5448a018b96ede18161abb5fee2/plugin-kit/tapdata-api/src/main/java/io/tapdata/entity/logger/TapLogger.java?_pjax=%23js-repo-pjax-container#L192-L195

**Comment by dobybros** [comment]
Fixed on develop-v2.7.0

**Comment by xbsura** [comment]
will close this issue after merge to master
