### ISSUE TITLE
MongoDB Atlas as Source & Target

### ISSUE THREAD

**Issue by tjworks** [tapdata/tapdata#564]
P1: Use Atlas Connection URL to connect to Atlas
P2: Use Oauth to connect to Atlas Cluster and select cluster

**Comment by dobybros** [comment]
我们发现atlas并没有提供oauth的接口来访问他的集群信息， 只能通过配置api key的方式， api key的方式访问目前能获得集群信息， 但是没有根据用户获得连接串的地方。 因此我们觉得直接配置数据库连接串其实也足够简单了， 所以没有在想配置api key来获得集群列表了

**Comment by dobybros** [comment]
目前已经开始在开发Mongodb Atlas了， 数据同步方面基本和Mongodb一致， 但是在连接测试方面有些不一样的地方， 还在解决。

**Comment by dobybros** [comment]
完成开发和测试验证， 可以做为Beta发布
