### ISSUE TITLE
数据库编码格式是否可以自动转换

### ISSUE THREAD

**Issue by snowcooled** [tapdata/tapdata#60]
在Oracle转换数据到MySQL时，MySQL不存在相应的数据表时创建数据表因为没有相应的编码导致创建失败。
[ERROR]  2022-08-02 14:17:28  [pool-34-thread-5]  io.tapdata.manager.TransformerJobManager 
Failed to create jdbc table  [***], sql: CREATE TABLE 
...省略
 default charset=ZHS16GBK , cause: Unknown character set: 'ZHS16GBK'; Will stop job
是否可以设置数据库的编码格式，或是对数据库的编码格式进行查询，对数据转换自动进行编码格式的匹配。

**Comment by xbsura** [comment]
@dobybros 在对应编码映射时, 我们目前的实现考虑不全面, 麻烦在接口中对此做定义, 走一下拉分支的流程, 反馈清楚一些

**Comment by dobybros** [comment]
我们先研究一下数据库间的字符集差异点， 先做设计。

**Comment by tjworks** [comment]
this was implemented
