### ISSUE TITLE
实现API数据的同步功能

### ISSUE THREAD

**Issue by snowcooled** [tapdata/tapdata#63]
能否实现API以及WebService类型数据的同步，涉及用户的登录，数据循环读取等

**Comment by xbsura** [comment]
已经在开发中, 可以跟进这个 issue @dobybros

**Comment by lordk911** [comment]
> 能否实现API以及WebService类型数据的同步，涉及用户的登录，数据循环读取等

+1

**Comment by tjworks** [comment]
please refer to the QuickAPI connector
